# Generated by Django 5.2.1 on 2025-05-26 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Airport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10, unique=True)),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name="scheduledflight",
            name="arrival_time",
        ),
        migrations.RemoveField(
            model_name="scheduledflight",
            name="route",
        ),
        migrations.AddField(
            model_name="scheduledflight",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name="scheduledflight",
            name="destination",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="arrivals",
                to="booking.airport",
            ),
        ),
        migrations.AddField(
            model_name="scheduledflight",
            name="origin",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="departures",
                to="booking.airport",
            ),
        ),
    ]
