# Generated by Django 5.2.1 on 2025-05-26 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0003_remove_aircraft_capacity_airport_timezone_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="airport",
            name="city",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="airport",
            name="timezone",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
