# Generated by Django 5.2.1 on 2025-05-27 13:19

import booking.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0004_airport_city_alter_airport_timezone"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduledflight",
            name="capacity",
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name="scheduledflight",
            name="arrival_time",
            field=models.DateTimeField(
                default=booking.models.today_midnight, null=True
            ),
        ),
        migrations.AlterField(
            model_name="scheduledflight",
            name="departure_time",
            field=models.DateTimeField(default=booking.models.today_midnight),
        ),
    ]
